In [1]:
print("hello world")

hello world


In [14]:
import numpy as np
a=12
b=11
ds=np.add(a,b)
print(ds)

23


In [23]:
import numpy as np
a=np.zeros(3)
print(a)

[0. 0. 0.]


In [20]:
# Python Program to create array with all zeros
import numpy as geek

a = geek.zeros(3, dtype = int)
print("Matrix a : \n", a)

b = geek.zeros([3, 3], dtype = int)
print("\nMatrix b : \n", b)


Matrix a : 
 [0 0 0]

Matrix b : 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [25]:
a=np.ones(3,dtype=int)
print(a)

[1 1 1]


In [46]:
import numpy as np

arr=np.random.rand(3,4)

# Print the array using a loop
for row in arr:
    for val in row:
        print(val, end=' ')
    print()


0.5126728707708105 0.7869232404143331 0.01668557296573392 0.857210775582557 
0.7171238336787668 0.13458012716842138 0.3935053044157628 0.9207185545496476 
0.12772793759784729 0.05664041531736752 0.8331318777576545 0.9354064821754793 


In [47]:
import numpy as np

# Initialize a numpy array of shape (3, 4) with zeros
arr = np.zeros((3, 4))

# Enter values into the array
arr[0, 0] = 1
arr[1, 2] = 3.14
arr[2, 1] = -2

# Print the array
print(arr)

[[ 1.    0.    0.    0.  ]
 [ 0.    0.    3.14  0.  ]
 [ 0.   -2.    0.    0.  ]]


In [51]:
import numpy as np

# Get the size of the array from the user
size = int(input("Enter size: "))

# Initialize a numpy array of shape (size) with zeros
arr = np.zeros((size),dtype=int)

# Enter values into the array using input statements
for i in range(size):
    value = int(input("Enter value {}: ".format(i+1)))
    arr[i] = value

# Print the array
print(arr)


Enter size: 3
Enter value 1: 1
Enter value 2: 2
Enter value 3: 3
[1 2 3]


In [57]:
import numpy as np

# Create a numpy array of integers
arr = np.array([1, 2, 4, 1, 2, 3, 1, 2, 1])

# Get the unique values and their counts using numpy's unique function
unique_vals, counts = np.unique(arr,return_index=True)

# Print the unique values and their counts
for val, count in zip(unique_vals, counts):
    print("{} occurs {} times".format(val, count))


1 occurs 0 times
2 occurs 1 times
3 occurs 5 times
4 occurs 2 times


In [58]:
import collections
x = np.array([1,2,3,4,5,1,2,1,9,1])
print("Original array:")
counter = collections.Counter(x)
print(counter)

Original array:
Counter({1: 4, 2: 2, 3: 1, 4: 1, 5: 1, 9: 1})


In [61]:
arr=np.array([1,2,4,5])
value=int(input("enter a number"))
count=np.count_nonzero(arr==value)
print("{} occurs {} times in the array.".format(value,count))

enter a number1
1 occurs 1 times in the array.


In [62]:
import numpy as np

# Create a numpy array of integers
arr = np.array([1, 2, 3, 4, 1, 2, 3, 1, 2, 1])

# Count the number of values in the array that are less than 4 using numpy's count_nonzero function
count = np.count_nonzero(arr < 4)

# Print the count
print("There are {} values in the array that are less than 4.".format(count))


There are 9 values in the array that are less than 4.


In [63]:
import numpy as np

# Create a numpy array of integers
arr = np.array([1, 2, 3, 4, 5])

# Specify the values to check
values = [2, 5, 7]

# Check whether each value is in the array using the in operator
for value in values:
    if value in arr:
        print("{} is in the array.".format(value))
    else:
        print("{} is not in the array.".format(value))


2 is in the array.
5 is in the array.
7 is not in the array.


In [64]:
import numpy as np

# Create a numpy array of integers
arr = np.array([1, 2, 3, 4, 5])

# Find the maximum and minimum element using numpy's max and min functions
max_element = np.max(arr)
min_element = np.min(arr)

# Print the maximum and minimum element
print("The maximum element is {} and the minimum element is {}.".format(max_element, min_element))


The maximum element is 5 and the minimum element is 1.
